git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: main
  maintainers:
    # marmarek
    - "0064428F455451B3EBE78A7F063938BA42CFA724"
    # simon
    - "274E12AB03F2FE293765FC06DA0434BC706E1FCF"

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3

mirrors:
  devuan:
    - https://pkgmaster.devuan.org/merged

deb:
  archive-keyring:
    devuan: /usr/share/keyrings/devuan-archive-keyring.gpg

distributions:
  - host-daedalus
  - vm-daedalus

components:
  - builder-debian:
      packages: false
  - vmm-xen:
      url: /home/user/github/qubes-devuan-dom0/upstream/qubes-vmm-xen
      verification-mode: insecure
  - qubes-release
  - linux-kernel
  - linux-utils
  - core-qrexec:
      url: /home/user/github/qubes-devuan-dom0/upstream/qubes-core-qrexec
      verification-mode: insecure
  - core-admin
  - gui-daemon
  - core-agent-linux
  - gui-agent-linux

executor:
  type: local
  options:
    directory: /home/user/github/qubes-devuan-dom0/artifacts/executor

stages:
  - fetch
  - prep
  - build
