
pre_install () {
  # Make sure there is a qubes group
  groupadd --force --system --gid 98 qubes
}

## arg 1:  the new package version
post_install() {
  ldconfig
  /bin/sv enable qubes-meminfo-writer-dom0.service > /dev/null 2>&1
  /bin/sv enable qubes-meminfo-writer.service > /dev/null 2>&1
}

post_upgrade() {
  ldconfig
}

post_remove() {
  ldconfig
  /bin/sv disable qubes-meminfo-writer.service > /dev/null 2>&1
  /bin/sv disable qubes-meminfo-writer.service > /dev/null 2>&1
}

